---

- name: Destroy previous venv
  file: path={{ application_home }}/venv state=absent

- name: Install ESGF SLCS Server from /code/esgf-slcs-server
  pip:
    name: /code/esgf-slcs-server
    virtualenv: "{{ application_home }}/venv"
    virtualenv_command: "{{ virtualenv_command }}"
    extra_args: "-e"
  become: yes
  become_user: "{{ application_user }}"
  notify:
    - Restart ESGF SLCS Server

- name: Set code_location fact
  set_fact:
    code_location: /code/esgf-slcs-server
