---

- name: Set code_location fact
  set_fact:
    code_location: "{{ application_home }}/src/esgf_slcs_server"

- name: Clone ESGF SLCS Server from Github
  git:
    repo: https://github.com/cedadev/esgf-slcs-server.git
    version: "{{ esgf_slcs_server_version }}"
    dest: "{{ code_location }}"
  become: yes
  become_user: "{{ application_user }}"

- name: Remove existing virtual env
  file: path={{ application_home }}/venv state=absent

- name: Install ESGF SLCS Server dependencies
  pip:
    requirements: "{{ code_location }}/requirements.txt"
    virtualenv: "{{ application_home }}/venv"
    virtualenv_command: "{{ virtualenv_command }}"
  become: yes
  become_user: "{{ application_user }}"

- name: Install ESGF SLCS Server
  pip:
    name: "{{ code_location }}"
    virtualenv: "{{ application_home }}/venv"
    virtualenv_command: "{{ virtualenv_command }}"
    extra_args: "--no-deps -e"
  become: yes
  become_user: "{{ application_user }}"
  notify:
    - Restart ESGF SLCS Server
