---

- name: Install gcc
  yum: name=gcc state=latest

- name: Install cryptography dependencies
  yum: name={{ item }} state=latest
  with_items:
    - libffi-devel
    - openssl-devel

- name: Install psycopg2 dependencies
  yum: name=postgresql-devel state=latest

- name: Create application user
  user: name={{ application_user }} state=present

- name: Set application home if not defined (1)
  shell: "getent passwd {{ application_user }} | cut -d: -f6"
  when: application_home is not defined
  register: application_home_result

- name: Set application home if not defined (2)
  set_fact:
    application_home: "{{ application_home_result.stdout }}"
  when: application_home is not defined

- include: install-{{ install_mode }}.yml
